### PR TITLE
Muskanbararia/i34/added cli support for decorators and vocab

### LINKED ISSUE #34: Add support for applying decorator set with CLI commands on a data-model
## Context
I wanted to apply decorator set config file on a data-model by using CLI commands.
## Expected Behavior
 When I use CLI commands and provide the decorator set  config file and a data-model .cto file it should be able to apply and provide the new data-model
## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/concerto)
- [ ] [GitHub Issues](https://github.com/accordproject/concerto/issues)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by muskanbararia**
feat: Added support for applying decorators and vocab to a model

# Closes #34 
Added command for applying a list of decorators and/or vocabularies to a given model. The output can be either json or cto, depending on the args

### Changes
- Added the relevant commands and the corresponding test cases with the test data
- Updated documentation in readme accordingly

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `main` from `fork:branchname`

### CODE REVIEW

File: lib/commands.js [hunk 1]
```diff
@@ -628,6 +629,47 @@ class Commands {
...
+     * @returns {string} - Depending on the options, CTO string or JSON string
+     */
+    static async decorate(modelFile, dcsFiles,vocFiles,options) {
+        try {
+            const modelContent = fs.readFileSync(path.resolve(modelFile), 'utf-8');
+            const allDCSFiles = dcsFiles ? dcsFiles.map(file => fs.readFileSync(file, 'utf8')) : [];
+            const allVocsFiles = vocFiles ? vocFiles.map(file => fs.readFileSync(file, 'utf8')) : [];
+            const modelManager = new ModelManager();
+            modelManager.addModel(modelContent);
+            let updatedModelManager = modelManager;
```
Comment (mttrbrts) [inline lib/commands.js:648]: What's the motivation for giving this variable an alias here? Are you concerned about mutating the instance, perhaps?

File: README.md [hunk 2]
```diff
@@ -115,6 +115,22 @@ Options:
...
+```
+concerto decorate
+
+apply the decorators and vocabs to the target models from given list of dcs files and vocab files
+
+Options:
+  --model      The CTO file                                   
+  --voc        The List of vocab files                                             
+  --dcs        The List of decorator command set files                                            
+  --f          output format (cto or json), default: cto
```
Comment (mttrbrts) [inline README.md:131]: Does `--model` support multiple values? We should make sure that we mirror the other commands.

Can you also add some non-abbreviated option flags too, please? 
For example, `--vocabulary`, `--decoratorCommandsSet`/`--decorator`, ``--format`.

Adding an optional `--output` flag would also help us to mirror the other commands.

File: lib/commands.js [hunk 3]
```diff
@@ -628,6 +629,47 @@ class Commands {
...
+            if (allDCSFiles.length > 0) {
```
Comment (mttrbrts) [inline lib/commands.js:649]: Given that you have the nice ternary initialisers above, I think that this condition is redundant. i.e. doing a `.forEach` over an empty array is perfectly fine.

**Review by mttrbrts — COMMENTED** [review]
A nice PR, thanks @muskanbararia!

My comments are mostly stylistic and related to standardisation of the command line flags.

File: lib/commands.js (hunk 1 above)
Comment (muskanbararia) [reply lib/commands.js:648]: I wanted to avoid mutating the original model in case I need it later on. I had also made modelManager a const for that very reason.  I can remove this alias since I didn't need the original later on.

File: README.md (hunk 2 above)
Comment (muskanbararia) [reply README.md:131]: `--model` only supports a single model file for this usecase. However, in the other commands, it is used for array of models (ex. `validate`).  In some places, an alias of `models` is provided.
Shall I change it to something else?

Comment (muskanbararia) [reply README.md:131]: Haven't really added support for writing to an external file. Will add it and provide `--output` flag too

Comment (mttrbrts) [reply README.md:131]: >  In some places, an alias of models is provided. Shall I change it to something else?

This should be considered a bug IMO. We should try to standardize the flags across commands, as far as possible. Can you get as close as you can for your new code, and open an issue for any other errant commands given that fixing them will be a breaking change, please?

**Review by mttrbrts — APPROVED** [review]

File: lib/commands.js [hunk 4]
```diff
@@ -628,6 +629,45 @@ class Commands {
...
+            const modelContent = fs.readFileSync(path.resolve(modelFile), 'utf-8');
+            const allDCSFiles = dcsFiles ? dcsFiles.map(file => fs.readFileSync(file, 'utf8')) : [];
+            const allVocsFiles = vocFiles ? vocFiles.map(file => fs.readFileSync(file, 'utf8')) : [];
+            let modelManager = new ModelManager();
+            modelManager.addModel(modelContent);
+            allDCSFiles.forEach(content => {
+                modelManager = DecoratorManager.decorateModels(modelManager, JSON.parse(content));
+            });
+            const vocManager = new VocabularyManager({ missingTermGenerator: VocabularyManager.englishMissingTermGenerator });
+            const namespace = modelManager.getModels().map(obj=>obj.name.replace(/\.cto$/, ''))[0];
```
Comment (dselman) [inline lib/commands.js:652]: The namespace for a ModelFile should be retrieved using modelFile.getNamespace() not inferred from its file name. The file name can be anything, or might even be absent, whereas the namespace is inside the ModelFile.

File: lib/commands.js [hunk 5]
```diff
@@ -628,6 +629,45 @@ class Commands {
...
+            allVocsFiles.forEach(content => {
+                vocManager.addVocabulary(content);
+            });
+            const vocabKeySet=(Object.keys(vocManager.vocabularies)).map(key=>key.replace(new RegExp(`^${namespace}/`), ''));
```
Comment (dselman) [inline lib/commands.js:656]: You should use VocabularManager.getVocabularies().map( voc => voc.getLocale() ) ...

File: lib/commands.js [hunk 6]
```diff
@@ -628,6 +629,45 @@ class Commands {
             inferredConcertoJsonModel.models[0]
         );
     }
+
+    /**
+     * Decorate a given model with given list of dcs and vocab files and print the result
+     * @param {string} modelFile - the model to which vocab and decorator has to be applied
+     * @param {string[]} dcsFiles - the decorator files to be applied to model
+     * @param {string[]} vocFiles - the vocab files to be applied to model
+     * @param {object} options - optional parameters
```
Comment (dselman) [inline lib/commands.js:638]: You should document what the options are here in jsdoc

File: lib/commands.js [hunk 7]
```diff
@@ -628,6 +629,45 @@ class Commands {
...
+            });
+            const vocabKeySet=(Object.keys(vocManager.vocabularies)).map(key=>key.replace(new RegExp(`^${namespace}/`), ''));
+            vocabKeySet.map(voc=>{
+                let commandSet = vocManager.generateDecoratorCommands(modelManager, voc);
+                modelManager = DecoratorManager.decorateModels(modelManager, commandSet);
+            });
+            let modelAst = modelManager.getModelFile(namespace).getAst();
+            let data =  (options.format === 'cto') ? Printer.toCTO(modelAst):JSON.stringify(modelAst);
+            if (options.output) {
+                fs.writeFileSync(options.output, data);
```
Comment (dselman) [inline lib/commands.js:664]: I'd expect the file name from the original ModelFile to be concatenated with the outputDir, so that a set on input model files get saved into an output directory. E.g. `./decorated/one.cto` and `./decorated/two.cto`.

**Review by dselman — CHANGES_REQUESTED** [review]
Great start!

File: lib/commands.js (hunk 4 above)
Comment (muskanbararia) [reply lib/commands.js:652]: `getNamespaces()` appends concerto namespaces as well. Filtering them out felt hacky. in `getmodels()` as far as what I saw, the name was `{namespace}.cto` and only had manually added ctos.
So I used this approach.

The other thing I can do is have a namespace array and populate it as below.
`let model=modelManager.addModel(modelContent);`
`namespaces.push(model.namespace)`

Which one do yoy think makes most sense?

File: lib/commands.js (hunk 5 above)
Comment (muskanbararia) [reply lib/commands.js:656]: Oh, I guess I missed out on `getLocale()`.
Thanks. Will update this.

File: lib/commands.js (hunk 4 above)
Comment (dselman) [reply lib/commands.js:652]: Getting the namespace from the model file using `modelFile.getNamespace()` and then building a CTO file name from that is the only reliable approach imo.

**Comment by muskanbararia** [comment]
@dselman I have added the testcase for dependent models as well

File: index.js [hunk 8]
```diff
@@ -408,6 +408,53 @@ require('yargs')
                 Logger.error(err.message);
             });
     })
+    .command('decorate', 'apply the decorators and vocabs to the target models from given list of dcs files and vocab files', yargs => {
+        yargs.demandOption('models', 'Please provide a model');
+        yargs.option('models', {
```
Comment (mttrbrts) [inline index.js:413]: Should this be singular, as per the docs above? Or otherwise we support both?

**Review by mttrbrts — APPROVED** [review]

File: index.js (hunk 8 above)
Comment (muskanbararia) [reply index.js:413]: I think we should support both. will update the PR accordingly.

Comment (muskanbararia) [reply index.js:413]: Updated PR.
